name: ci

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Revise BAdvComp - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Test Server
        working-directory: ./src/server
        run: |
          rustup update ${{ matrix.toolchain }} 
          rustup default ${{ matrix.toolchain }}
          cargo build --verbose
          cargo test --verbose

